---
- name: This playbook is to copy a file
  hosts: all
  become: yes

  tasks:
  - name: copy a file
    copy:
            src: /home/ansadmin/index.html
            dest: /home/ansadmin
            owner: ansadmin
            group: ansadmin
            mode: 0666
...            
