---
- name: This playbook is to install webserver with notify and handler
  hosts: all
  become: yes

  tasks:
  - name: This is to install httpd package
    yum: 
       name: httpd
       state: installed
    notify: starting httpd
 
  handlers:
  - name: starting httpd
    service:
       name: httpd
       state: started
...
