---
- name: This playbook is to install multiple packages
  hosts: all
  become: yes

  tasks:
  - name: This is to install multiple packages
    yum:
            name: [ 'git', 'mysql', 'tree', 'docker*', 'wget', 'which']
            state: present
...
